/* VectorOne Student Management — frontend JSON fixtures and API integration placeholders. */
(function () {
  'use strict';
  const API = { students: '/api/admin/students', importCsv: '/api/admin/students/import', exportCsv: '/api/admin/students/export' };
  const students = [
    {id:'VO2024001',name:'Aarav Mehta',dept:'Computer Science',year:'2',division:'A',semester:'3',email:'aarav.mehta@vectorone.edu',phone:'+91 98765 10234',attendance:94,status:'Active'},
    {id:'VO2024002',name:'Diya Sharma',dept:'Information Technology',year:'3',division:'B',semester:'5',email:'diya.sharma@vectorone.edu',phone:'+91 98765 21879',attendance:91,status:'Active'},
    {id:'VO2024003',name:'Rohan Iyer',dept:'Mechanical Engineering',year:'4',division:'A',semester:'7',email:'rohan.iyer@vectorone.edu',phone:'+91 98765 33210',attendance:87,status:'Active'},
    {id:'VO2024004',name:'Ananya Gupta',dept:'Computer Science',year:'1',division:'C',semester:'1',email:'ananya.gupta@vectorone.edu',phone:'+91 98765 44661',attendance:96,status:'Active'},
    {id:'VO2024005',name:'Kabir Khan',dept:'Electronics',year:'2',division:'B',semester:'3',email:'kabir.khan@vectorone.edu',phone:'+91 98765 55902',attendance:74,status:'Suspended'},
    {id:'VO2024006',name:'Meera Nair',dept:'Business Administration',year:'4',division:'A',semester:'7',email:'meera.nair@vectorone.edu',phone:'+91 98765 66913',attendance:89,status:'Graduated'},
    {id:'VO2024007',name:'Vivaan Patel',dept:'Information Technology',year:'1',division:'A',semester:'1',email:'vivaan.patel@vectorone.edu',phone:'+91 98765 77324',attendance:92,status:'Active'},
    {id:'VO2024008',name:'Ishita Roy',dept:'Computer Science',year:'3',division:'C',semester:'5',email:'ishita.roy@vectorone.edu',phone:'+91 98765 88535',attendance:98,status:'Active'}
  ];
  const nav = ['Dashboard','Students','Faculty','Departments','Courses','Attendance','Notices','Events','Assignments','Resources','Messages','Reports','Analytics','Settings','Profile'];
  const iconSet = ['⌂','◉','♙','▦','▤','◷','▣','◇','✓','▱','◌','◫','◌','⚙','◯'];
  const $ = function (id) { return document.getElementById(id); };
  function currentTheme() { return document.documentElement.getAttribute('data-theme') === 'dark' ? 'dark' : 'light'; }
  function applyTheme(theme) { document.documentElement.setAttribute('data-theme', theme); localStorage.setItem('cc-theme', theme); const dark = theme === 'dark'; $('themeToggle').setAttribute('aria-pressed', String(dark)); $('themeToggle').setAttribute('aria-label', dark ? 'Switch to light theme' : 'Switch to dark theme'); }
  applyTheme(currentTheme()); $('themeToggle').addEventListener('click', function () { applyTheme(currentTheme() === 'dark' ? 'light' : 'dark'); });
  const sidebar = $('sidebar'), backdrop = $('sidebarBackdrop'); function closeDrawer(){sidebar.classList.remove('is-open');backdrop.classList.remove('is-visible');$('sidebarToggle').setAttribute('aria-expanded','false');}$('sidebarToggle').addEventListener('click',function(){if(innerWidth<=1024){const open=!sidebar.classList.contains('is-open');sidebar.classList.toggle('is-open',open);backdrop.classList.toggle('is-visible',open);this.setAttribute('aria-expanded',String(open));}else{document.body.classList.toggle('sidebar-collapsed');}});backdrop.addEventListener('click',closeDrawer);addEventListener('resize',function(){if(innerWidth>1024)closeDrawer();});
  $('adminNav').innerHTML=nav.map(function(item,index){return '<a href="'+(item==='Dashboard'?'dashboard.html':'#'+item.toLowerCase())+'" class="sidebar-link '+(item==='Students'?'is-active':'')+'"><span class="nav-icon">'+iconSet[index]+'</span><span>'+item+'</span></a>';}).join('');
  function popover(button,panel){$(button).addEventListener('click',function(e){e.stopPropagation();const open=$(panel).hidden;document.querySelectorAll('.notification-panel,.user-dropdown').forEach(function(x){x.hidden=true;});$(panel).hidden=!open;this.setAttribute('aria-expanded',String(open));});document.addEventListener('click',function(e){if(!$(panel).contains(e.target)&&!$(button).contains(e.target)){$(panel).hidden=true;$(button).setAttribute('aria-expanded','false');}});} popover('notificationBtn','notificationPanel');popover('userMenuBtn','userDropdown');
  $('notificationList').innerHTML=['4 new student registrations await approval','Attendance report has been generated','New scholarship notice published','CSV import completed successfully'].map(function(text,index){return '<li class="notification-item is-unread"><span class="notification-dot"></span><div><p class="notification-text">'+text+'</p><span class="notification-time">'+(index+1)+' hour ago</span></div></li>';}).join(''); $('markAllReadBtn').addEventListener('click',function(){document.querySelectorAll('.notification-item').forEach(function(x){x.classList.remove('is-unread');});$('notificationBadge').textContent='0';});
  const globalData=students.map(function(s){return {title:s.name,type:'Student'};}).concat([{title:'Student admissions report',type:'Report'},{title:'Faculty directory',type:'Faculty'}]); function renderGlobalSearch(){const q=$('globalSearch').value.toLowerCase().trim(),items=globalData.filter(function(item){return item.title.toLowerCase().includes(q)||item.type.toLowerCase().includes(q);});$('searchResultsList').innerHTML=items.map(function(item){return '<li><button type="button" class="search-item"><span class="search-item-text">'+item.title+'</span><span class="search-item-type">'+item.type+'</span></button></li>';}).join('');}$('globalSearch').addEventListener('focus',function(){$('searchPanel').hidden=false;renderGlobalSearch();});$('globalSearch').addEventListener('input',function(){$('searchPanel').hidden=false;renderGlobalSearch();});$('searchClear').addEventListener('click',function(){$('globalSearch').value='';$('globalSearch').focus();renderGlobalSearch();});document.addEventListener('keydown',function(e){if(e.key==='/'&&document.activeElement!==$('globalSearch')&&!['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName)){e.preventDefault();$('globalSearch').focus();}if(e.key==='Escape'){closeDrawer();$('searchPanel').hidden=true;closeModal();}});
  $('studentStats').innerHTML=[['Total Students','4,826','+8.4% this term','blue'],['Active Students','4,341','89.9% enrolled','green'],['Graduated Students','1,284','+214 this year','purple'],['New Admissions','218','+32 this week','orange']].map(function(s){return '<article class="stat-card stat-card--'+s[3]+'"><div class="stat-card-top"><div class="stat-icon stat-icon--'+s[3]+'">◉</div></div><p class="stat-value">'+s[1]+'</p><p class="stat-label">'+s[0]+'</p><span class="stat-trend stat-trend--up">↗ '+s[2]+'</span></article>';}).join('');
  const filters=['departmentFilter','yearFilter','divisionFilter','semesterFilter','statusFilter']; const depts=[...new Set(students.map(function(s){return s.dept;}))];$('departmentFilter').innerHTML='<option value="">Department</option>'+depts.map(function(d){return '<option>'+d+'</option>';}).join('');
  function initials(name){return name.split(' ').map(function(part){return part[0];}).join('');} function filtered(){const q=$('studentSearch').value.trim().toLowerCase();return students.filter(function(s){return (!q||Object.values(s).join(' ').toLowerCase().includes(q))&&filters.every(function(id){const value=$(id).value;const key={departmentFilter:'dept',yearFilter:'year',divisionFilter:'division',semesterFilter:'semester',statusFilter:'status'}[id];return !value||s[key]===value;});}).sort(function(a,b){const sort=$('sortStudents').value;return sort==='attendance'?b.attendance-a.attendance:String(a[sort]).localeCompare(String(b[sort]));});}
  function renderStudents(){const data=filtered();$('studentsBody').innerHTML=data.map(function(s){const state=s.status.toLowerCase();return '<tr><td>'+s.id+'</td><td><span class="student-photo">'+initials(s.name)+'</span></td><td class="student-name">'+s.name+'</td><td>'+s.dept+'</td><td>'+s.year+'</td><td>'+s.division+'</td><td>'+s.semester+'</td><td>'+s.email+'</td><td>'+s.phone+'</td><td><span class="attendance">'+s.attendance+'%</span></td><td><span class="status-pill-student '+state+'">'+s.status+'</span></td><td><div class="student-actions"><button class="row-action" data-op="view" data-id="'+s.id+'" aria-label="View '+s.name+'">View</button><button class="row-action" data-op="edit" data-id="'+s.id+'" aria-label="Edit '+s.name+'">Edit</button><button class="row-action" data-op="more" data-id="'+s.id+'" aria-label="More actions for '+s.name+'">•••</button></div></td></tr>';}).join('');$('studentCount').textContent=data.length+' of '+students.length+' students';$('studentsEmpty').hidden=!!data.length;} filters.concat(['studentSearch','sortStudents']).forEach(function(id){$(id).addEventListener(id==='studentSearch'?'input':'change',renderStudents);});$('clearFilters').addEventListener('click',function(){filters.forEach(function(id){$(id).value='';});$('studentSearch').value='';$('sortStudents').value='name';renderStudents();});renderStudents();
  $('admissionsList').innerHTML=students.slice(0,3).map(function(s,index){return '<div class="compact-row"><span class="student-photo">'+initials(s.name)+'</span><div class="row-copy"><strong>'+s.name+'</strong><span>'+s.dept+'</span></div><time>'+[12,34,56][index]+'m</time></div>';}).join('');$('approvalsList').innerHTML=['Mira Kapoor · CS','Dev Patel · IT','Nisha Jain · BBA'].map(function(item){return '<div class="compact-row"><div class="row-copy"><strong>'+item+'</strong><span>Registration awaiting review</span></div><button class="link-inline" type="button">Review</button></div>';}).join('');$('studentQuickActions').innerHTML=['Add Student','Import CSV','Export CSV','Bulk Update'].map(function(item){return '<button type="button" class="quick-action" data-quick="'+item+'"><span class="nav-icon">＋</span><span>'+item+'</span></button>';}).join('');$('departmentStats').innerHTML=depts.slice(0,4).map(function(dept,index){const value=[92,76,64,49][index];return '<div class="department-stat"><strong>'+dept+'</strong><span>'+value+'%</span><div class="department-bar"><i style="width:'+value+'%"></i></div></div>';}).join('');
  const modal=$('studentModal'),modalTitle=$('modalTitle'),modalContent=$('modalContent'),modalActions=$('modalActions');let activeStudent=null;function openModal(){modal.hidden=false;requestAnimationFrame(function(){modal.classList.add('is-open');});document.body.style.overflow='hidden';$('modalClose').focus();}function closeModal(){modal.classList.remove('is-open');document.body.style.overflow='';setTimeout(function(){modal.hidden=true;},180);}$('modalClose').addEventListener('click',closeModal);modal.addEventListener('click',function(e){if(e.target===modal)closeModal();});
  function detailContent(s){return '<div class="student-detail"><div class="student-detail-grid">'+[['Student ID',s.id],['Full name',s.name],['Department',s.dept],['Year & Division',s.year+' · '+s.division],['Semester',s.semester],['Attendance',s.attendance+'%'],['Email',s.email],['Phone',s.phone],['Status',s.status]].map(function(row){return '<div><span>'+row[0]+'</span><strong>'+row[1]+'</strong></div>';}).join('')+'</div></div>';}function formContent(s){s=s||{name:'',id:'VO2024',dept:depts[0],year:'1',division:'A',semester:'1',email:'',phone:'',status:'Active'};return '<form class="student-form" id="studentForm">'+[['Full name','name'],['Student ID','id'],['Email','email'],['Phone','phone']].map(function(x){return '<label>'+x[0]+'<input name="'+x[1]+'" value="'+s[x[1]]+'" required></label>';}).join('')+'<label>Department<select name="dept">'+depts.map(function(d){return '<option '+(d===s.dept?'selected':'')+'>'+d+'</option>';}).join('')+'</select></label><label>Year<select name="year">'+['1','2','3','4'].map(function(d){return '<option '+(d===s.year?'selected':'')+'>'+d+'</option>';}).join('')+'</select></label><label>Division<select name="division">'+['A','B','C'].map(function(d){return '<option '+(d===s.division?'selected':'')+'>'+d+'</option>';}).join('')+'</select></label><label>Semester<select name="semester">'+['1','3','5','7'].map(function(d){return '<option '+(d===s.semester?'selected':'')+'>'+d+'</option>';}).join('')+'</select></label></form>';}
  function modalButtons(primary,label){modalActions.innerHTML='<button type="button" class="btn btn-outline" id="cancelModal">Cancel</button><button type="button" class="btn '+(primary==='delete'?'btn-outline':'btn-primary')+'" id="confirmModal">'+label+'</button>';$('cancelModal').addEventListener('click',closeModal);}
  document.addEventListener('click',function(e){const btn=e.target.closest('[data-op]');if(!btn)return;activeStudent=students.find(function(s){return s.id===btn.dataset.id;});if(btn.dataset.op==='view'){modalTitle.textContent='View Student';modalContent.innerHTML=detailContent(activeStudent);modalActions.innerHTML='<button type="button" class="btn btn-primary" id="closeView">Close</button>';$('closeView').addEventListener('click',closeModal);}else if(btn.dataset.op==='edit'){modalTitle.textContent='Edit Student';modalContent.innerHTML=formContent(activeStudent);modalButtons('save','Save changes');$('confirmModal').addEventListener('click',function(){const form=new FormData($('studentForm'));Object.keys(Object.fromEntries(form)).forEach(function(key){activeStudent[key]=form.get(key);});closeModal();renderStudents();});}else{modalTitle.textContent='Student Actions';modalContent.innerHTML='<div class="modal-message">Choose an administrative action for <strong>'+activeStudent.name+'</strong>.</div>';modalActions.innerHTML='<button class="btn btn-outline" type="button" id="resetPassword">Reset Password</button><button class="btn btn-outline" type="button" id="suspendStudent">'+(activeStudent.status==='Suspended'?'Restore':'Suspend')+'</button><button class="btn btn-outline" type="button" id="deleteStudent">Delete</button>';$('resetPassword').addEventListener('click',function(){this.textContent='Reset link sent';});$('suspendStudent').addEventListener('click',function(){activeStudent.status=activeStudent.status==='Suspended'?'Active':'Suspended';closeModal();renderStudents();});$('deleteStudent').addEventListener('click',function(){modalTitle.textContent='Delete Student';modalContent.innerHTML='<div class="modal-message">Delete <strong>'+activeStudent.name+'</strong>? This frontend demo will remove the record from the current table only.</div>';modalButtons('delete','Delete student');$('confirmModal').addEventListener('click',function(){students.splice(students.indexOf(activeStudent),1);closeModal();renderStudents();});});}openModal();});
  function openAdd(){modalTitle.textContent='Add Student';modalContent.innerHTML=formContent();modalButtons('save','Add student');$('confirmModal').addEventListener('click',function(){const data=Object.fromEntries(new FormData($('studentForm')));data.attendance=100;data.status='Active';students.unshift(data);closeModal();renderStudents();});openModal();}$('addStudentBtn').addEventListener('click',openAdd);document.querySelectorAll('[data-quick]').forEach(function(btn){btn.addEventListener('click',function(){if(btn.dataset.quick==='Add Student')openAdd();else{const original=btn.textContent;btn.textContent='Ready';setTimeout(function(){btn.textContent=original;},1000);}});});['importBtn','exportBtn','refreshBtn'].forEach(function(id){$(id).addEventListener('click',function(){const original=this.textContent;this.textContent=id==='refreshBtn'?'Refreshed':'Ready';setTimeout(()=>this.textContent=original,900);renderStudents();});});
}());
